services:
  magic-folder:
    image: magic-folder:latest
    build: .
    container_name: magic-folder
    restart: unless-stopped
    
    extra_hosts:
      - "VPOHO:192.168.0.5"
    
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined

    environment:
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
      - SMB_DOMAIN=${SMB_DOMAIN}